version: '3.0'

services:

  web:
    container_name: web
    image: finalproject/airdns
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:latest
    hostname: redis
    ports:
      - 6379:6379