spring:
  datasource:
    driver-class-name: ${DB_DRIVER}
    username: ${DB_USER}
    url: ${DB_URL}
    password: ${DB_PASSWORD}
  jackson:
    time-zone: Asia/Seoul
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        use_sql_comments: 'true'
        show_sql: 'true'
#        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: update
  jwt:
    secret: ${JWT_SECRET}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  servlet:
    multipart:
      max-file-size: 10MB # 한개 파일의 최대 사이즈 (default: 1MB)
      max-request-size: 100MB # 한개 요청의 최대 사이즈 (default: 10MB)
#swagger
  mvc:
    path match:
      matching-strategy: ant_path_matcher
#spring docs

springdoc:
  swagger-ui:
    tags-sorter: alpha

#AWS S3
cloud:
  aws:
    s3:
      bucket: ${AWS_BUCKET_NAME}
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${AWS_ACCESSKEY}
      secretKey: ${AWS_SECRETKEY}


