spring:
  datasource:
    driver-class-name: ${DB_DRIVER}
    username: ${DB_USER}
    url: ${DB_URL}
    password: ${DB_PASSWORD}
  jackson:
    time-zone: Asia/Seoul
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        use_sql_comments: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update
