name: 'air_DnS backend CD'
on:
  push:
    branches:
      # 임시
      - "feat/cicd"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # JDK17 설치
      - name: setup jdk
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

      # 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Test code 미포함 빌드
      - name: Spring Boot Application Build
        run: ./gradlew build -x test

      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Image Build
      - name: Docker Image Build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }} .

      # Image push
      - name: DockerHub Push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }}

      - name: Run Application
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          timeout: 2m
          command_timeout: 10m
  #        script: |
  #          sudo docker kill ${{ secrets.PROJECT_NAME }}
  #          sudo docker rm -f ${{ secrets.PROJECT_NAME }}
  #          sudo docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }}
  #          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }}
  #
  #          sudo docker run \
  #            -e REDIS_HOST=${{ secrets.REDIS_HOST }} \
  #            -e REDIS_PORT=${{ secrets.REDIS_PORT }} \
  #            -e DB_DRIVER=${{ secrets.DB_DRIVER }} \
  #            -e DB_USER=${{ secrets.DB_USER }} \
  #            -e AWS_ACCESSKEY=${{ secrets.AWS_ACCESSKEY }} \
  #            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
  #            -e KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }} \
  #            -e KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }}
  #            -p ${{ secrets.PORT }}:${{ secrets.PORT }} \
  #                    --name ${{ secrets.PROJECT_NAME }} \
  #                    -d ${{ secrets.DOCKERHUB_USERNAME}}/${{ secrets.PROJECT_NAME }}